sudo: false
language: python
python: 3.7
cache: pip
fast_finish: true
addons:
  apt_packages:
    - pandoc
env:
  global:
    - buildnum=$TRAVIS_BUILD_NUMBER
stages:
  - name: validate
  - name: test
  - name: package
jobs:
  include:
    - stage: validate
      script:
        - make install
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: test
      script:
        - make install
        - make test
    - stage: package
      script:
        - make install
        - make package
