language: python
python: 3.7
cache: pip
addons:
  apt_packages:
    - pandoc
#env:
#  global:
#    - buildnum=$TRAVIS_BUILD_NUMBER
stages:
  - name: validate
  - name: unit_test
  - name: integration_test
  - name: package
  - name: publish
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - make install
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: unit-test
      script:
        - make install
        - make unit_test
    - stage: integration-test
      if: type = push
      script:
        - make install
        - make integration_test
    - stage: package
      script:
        - make install
        - make package
    - stage: publish
      if: tag =~ ^v
      script:
        - make install
        - make publish
        - bumpversion patch --config-file setup.cfg
        - openssl aes-256-cbc -K $encrypted_746a8d15852c_key -iv $encrypted_746a8d15852c_iv -in github-deploy-key-jccli.enc -out ~\/.ssh/github-deploy-key-jccli -d
        - chmod 600 ~/.ssh/github-deploy-key-jccli && eval "$(ssh-agent -s)" && ssh-add ~/.ssh/github-deploy-key-jccli
        - git add -u && git commit -m "[ci skip] bump version" && git push origin HEAD:master
