sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
env:
  global:
    - buildnum=$TRAVIS_BUILD_NUMBER
install:
  - pip install pre-commit
stages:
  - name: validate
jobs:
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
        - make install
        - make build
        - make test
