sudo: false
language: python
python: 3.7
cache: pip
fast_finish: true
addons:
  apt_packages:
    - pandoc
env:
  global:
    - buildnum=$TRAVIS_BUILD_NUMBER
stages:
  - name: validate
  - name: unit_test
  - name: integration_test
  - name: package
  - name: publish
jobs:
  include:
    - stage: validate
      script:
        - make install
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: unit-test
      script:
        - make install
        - make unit_test
    - stage: integration-test
      if: type = push
      script:
        - make install
        - make integration_test
    - stage: package
      script:
        - make install
        - make package
    - stage: publish
      if: tag =~ ^v
      script:
        - make install
        - make publish
        - bumpversion patch --config-file setup.cfg
        - git add -u && git commit -m "[ci skip] bump version" && git push origin HEAD:master
